---
# tasks file for mahmoud_role
- name: task0 check os
  fail:
    msg: "Better Call Saul !!"
  when: ansible_facts.distribution != "RedHat"

- name: task1 install apache
  dnf:
    name: "{{ SW }}"
    state: present
  notify: upload

- name: task2 enable apache
  service:
    name: "{{ SW }}"
    state: started
    enabled: yes

- name: task3 Backup httpd.conf
  copy:
    src: /etc/httpd/conf/httpd.conf
    dest: /etc/httpd/conf/httpd.conf.bak
    remote_src: yes

- name: task4 Change Apache port to 88
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen '
    state: present
    line: 'Listen 88'

- name: task5 Allow port 88
  command: semanage port -m -t http_port_t -p tcp 88
  args:
    warn: false
  ignore_errors: true

- name: task6 open http
  firewalld:
    port: 88/tcp
    state: enabled
    permanent: yes
    immediate: yes

- name: task7 restart apache
  service:
    name: "{{ SW }}"
    state: restarted


- name: copy image
  copy:
    src: ./ansible.jpg
    dest: /var/www/html/ansible.jpg
    mode: '0644'
